## Project-wide Gradle settings.

# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Use this to specify the JVM toolchain version
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true

# AndroidX support
android.useAndroidX=true

# Optimize build speed by using non-transitive R classes
android.nonTransitiveRClass=true
android.nonFinalResIds=true

# Enable parallel execution
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
